
/**:
  ros__parameters:
    frame_id: "gps"
    capacity_bytes: 1024
    connection_type: "serial"
    serial:
      device_name: "/dev/ttyUSB1"
      baud_rate: 460800
      flow_control: "none"
      parity: "none"
      stop_bits: "1"
    ip:
      addr: "192.168.55.100"
      port: "2101"