name: ROS2 CI Workflow

on:
  pull_request:
    branches:
      - stable
  push:
    branches:
      - stable

jobs:
  build-test-ros2:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: "galactic"
          - ros_distro: "humble"
    container:
      image: osrf/ros:${{ matrix.ros_distro }}-desktop
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Dependencies
        run: |
          bash -c 'source /opt/ros/${{ matrix.ros_distro }}/setup.bash; \
          make rosdep-install'
      - name: Build Workspace
        run: |
          bash -c 'source /opt/ros/${{ matrix.ros_distro }}/setup.bash; \
          make'
      - name: Run Tests
        run: |
          bash -c 'source /opt/ros/${{ matrix.ros_distro }}/setup.bash; \
          make test'